# Generated by Django 3.2.7 on 2021-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='news_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('GENEL', 'Genel'), ('ELEKTRONIK', 'Elektronik'), ('YAZILIM', 'Yazılım'), ('EGLENCE', 'Eğlence')], max_length=20, null=True),
        ),
    ]
